// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, Link, matchPath, matchRoutes, Navigate, NavLink, Outlet, useLocation, useMatch, useNavigate, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, renderClient, useRouteData } from '/Users/sensoro/Documents/projects/sensoro-github/plugins/node_modules/.pnpm/@umijs+renderer-react@4.0.0-rc.15_react-dom@18.1.0+react@18.1.0/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/sensoro/Documents/projects/sensoro-github/plugins/node_modules/.pnpm/umi@4.0.0-rc.15_08f259ad4a5de862c0faa45cd9ba30ff/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
// plugins
export { Provider, useModel } from '/Users/sensoro/Documents/projects/sensoro-github/plugins/examples/lins-core/src/.umi/plugin-model';
export { terminal } from '/Users/sensoro/Documents/projects/sensoro-github/plugins/examples/lins-core/src/.umi/plugin-terminal';
// plugins types.d.ts
